GlucoseMonitor/urls.py
from django.conf.urls import url, include, handler400, handler403, handler404, handler500
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import bad_request, permission_denied, page_not_found, server_error

urlpatterns = [
    url(r'^', include('favicon.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^measures/', include('measures.urls')),
]

handler400 = 'GlucoseMonitor.views.bad_request'
handler403 = 'GlucoseMonitor.views.permission_denied'
handler404 = 'GlucoseMonitor.views.page_not_found'
handler500 = 'GlucoseMonitor.views.server_error'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from accounts import views

urlpatterns = [
    url(r'^$', views.login),
    url(r'^accounts/login', views.login),
    url(r'^accounts/logout', views.logout),
    url(r'^accounts/signup', views.signup),
    url(r'^accounts/contact', views.contact),
    url(r'^accounts/set_password', views.set_password),
    url(r'^accounts/lookup/(?P<field>[A-Za-z0-9_]+)/(?P<value>.+)', views.lookup),
    url(r'^accounts/check_password/(?P<password>.+)', views.check_password),
]

measures/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^list$', views.measures_list),
    url(r'^delete/(\d+)', views.delete_measure),
    url(r'^edit/(\d+)', views.edit_measure),
    url(r'^export_pdf$', views.export_pdf),
]

measures/models.py
from django.db import models
from django.contrib.auth.models import User

class GlucoseMeasure(models.Model):
    MEASURE_TYPES = (
        ('FST', 'Em jejum'),
        ('AFM', 'Após refeição'),
    )
    value = models.DecimalField(null=False, blank=False, max_digits=5, decimal_places=2)
    datetime = models.DateTimeField(null=False, blank=False)
    notes = models.CharField(null=True, blank=True, max_length=140)
    measure_type = models.CharField(null=False, blank=False, max_length=3, choices=MEASURE_TYPES, default='FST')
    user = models.ForeignKey(User, null=False, blank=False)

measures/forms.py
from django import forms
from measures.models import GlucoseMeasure
from parsley.decorators import parsleyfy

attrs = {
    'value'       : {'class': 'form-control'} ,
    'datetime'    : {'class': 'form-control'} ,
    'measure_type': {'class': 'form-control'} ,
    'notes'       : {'class': 'form-control', 'rows': 4} ,
}

@parsleyfy
class GlucoseMeasureForm(forms.ModelForm):
    class Meta:
        model = GlucoseMeasure
        fields = ['measure_type', 'value', 'datetime', 'notes', 'user']
        widgets = {
            'value'       : forms.NumberInput(attrs=attrs['value']),
            'datetime'    : forms.DateTimeInput(attrs=attrs['datetime']),
            'notes'       : forms.Textarea(attrs=attrs['notes']),
            'measure_type': forms.Select(attrs=attrs['measure_type']),
            'user'        : forms.HiddenInput()
        }
        labels = {
            'value'       : 'Valor',
            'datetime'    : 'Data/Hora',
            'notes'       : 'Notas',
            'measure_type': 'Tipo',
            'user'        : 'Usuário',
        }
        parsley_extras = {
            'value'   : {
                'pattern'         : '^\d{1,3}([\.\,]\d{0,2})?$',
                'pattern-message' : 'Por favor insira um número válido.',
                'type-message'    : 'Por favor insira um número válido.',
                'required-message': 'Este campo é obrigatório.',
            },
            'datetime': {
                'pattern'         : '^([0-2][0-9]|[3][0-1])/([0][1-9]|[1][0-2])\/(\d{4})\ ([0-1][0-9]|[2][0-3])\:([0-5][0-9])(:([0-5][0-9]))?$',
                'pattern-message' : 'Por favor insira uma data/hora válida.',
            }
        }

measures/views.py
import json
from datetime import datetime, timedelta, time
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from measures.encoders import DecimalEncoder, DateTimeEncoder
from measures.forms import GlucoseMeasureForm
from measures.models import GlucoseMeasure
from measures.report.generator import ReportGenerator
from measures.querybusiness import peform_query
from measures.period import get_period_params, get_period_interval, period_param_is_valid
from django.db.models import Avg, Max, Min
from django.utils import timezone

@login_required
@period_param_is_valid
def index(request):
    if request.method == 'POST':
        path = request.META['HTTP_REFERER']
        form = GlucoseMeasureForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Medição adicionada com sucesso')
            return redirect(path)
    else:
        form = GlucoseMeasureForm()

    # Listen period
    period, period_begin, period_end = get_period_params(request)

    # Get queryset
    queryset = peform_query(request)

    # Measure type queryset separation
    fst_queryset = queryset.filter(measure_type='FST')
    afm_queryset = queryset.filter(measure_type='AFM')

    # Projections data
    values     = list(queryset.reverse().values_list('value', flat=True))
    datetimes  = list(queryset.reverse().values_list('datetime', flat=True))

    # Context dict
    context = {
        'form'        : form,
        'period'      : period,
        'period_begin': period_begin,
        'period_end'  : period_end,
        'tab'         : 'home',
        'queryset'    : queryset,
        'last'        : queryset[:5],
        'distribution': {
            'hypo': fst_queryset.filter(value__lte=70).count() + afm_queryset.filter(value__lte=70).count(),
            'norm': fst_queryset.filter(value__gt=70,  value__lte=100).count() + afm_queryset.filter(value__gt=70,  value__lte=140).count(),
            'pre' : fst_queryset.filter(value__gt=100, value__lte=126).count() + afm_queryset.filter(value__gt=140, value__lte=200).count(),
            'high': fst_queryset.filter(value__gt=126).count() + afm_queryset.filter(value__gt=200).count(),
        },
        'overlay': {
            'data'  : json.dumps(values,    cls=DecimalEncoder),
            'labels': json.dumps(datetimes, cls=DateTimeEncoder),
        },
        'average': queryset.aggregate(Avg('value'))['value__avg'],
        'max'    : queryset.aggregate(Max('value'))['value__max'],
        'min'    : queryset.aggregate(Min('value'))['value__min'],
    }

    return render(request, 'measures/index.html', context)



@login_required
@period_param_is_valid
def measures_list(request):
    queryset = peform_query(request)
    period, period_begin, period_end = get_period_params(request)

    # Prepare paginator
    paginator = Paginator(queryset, 15)
    page = request.GET.get('page', 1)

    # Paginate queryset
    try:
        paginated_list = paginator.page(page)
    except PageNotAnInteger:
        paginated_list = paginator.page(1)
    except EmptyPage:
        paginated_list = paginator.page(paginator.num_pages)

    context = {
        'tab'         : 'list',
        'period'      : period,
        'period_begin': period_begin,
        'period_end'  : period_end,
        'queryset'    : paginated_list,
    }
    return render(request, 'measures/list.html', context)


@login_required
def delete_measure (request, id):
    # Get path to return
    path = request.META.get('HTTP_REFERER', 'measures/list')
    # User only can delete your own measures
    instance = get_object_or_404(GlucoseMeasure, pk=id)
    if instance.user.id != request.user.id:
        raise Http404

    instance.delete()
    messages.success(request, 'Medição excluída com sucesso')
    return redirect(path)


@login_required
def edit_measure(request, id):
    # Get path to return
    path = request.META['HTTP_REFERER']
    # User only can edit your own measures
    instance = get_object_or_404(GlucoseMeasure, pk=id)
    if instance.user.id != request.user.id:
        raise Http404

    form =  GlucoseMeasureForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        path = request.POST.get('return_path', '/measures/list')
        if form.is_valid():
            form.save()
            messages.success(request, 'Medição editada com sucesso')
            return redirect(path)

    context = {
        'form': form,
        'return_path': path,
    }
    return render(request, 'measures/edit.html', context)

@login_required
@period_param_is_valid
def export_pdf(request):
    queryset = peform_query(request)
    period_interval = get_period_interval(request)

    response = HttpResponse(content_type='application/pdf')
    filename = 'Relatorio_' + datetime.now().strftime('%Y_%m_%d__%H_%M')
    response['Content-Disposition'] ='attachement; filename=%s.pdf' % (filename)

    report = ReportGenerator()
    pdf = report.generatePdfReport(queryset, period_interval)
    response.write(pdf)
    return response

measures/templates/measures/base.html
{% extends "base.html" %}


{% block main_content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            {% include "measures/sidebar.html" %}
        </div>
        <div class="col-md-9">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}



{% block main_script %}
<script src="/static/measures/js/render_charts.js" charset="utf-8"></script>
<script src="/static/measures/js/utils.js" charset="utf-8"></script>
<script>
    var parsley_rules = {
        'data-parsley-required': "true",
        'data-parsley-required-message':"Este campo é obrigatório",
    }

    var sidebarLink = "?period={{ period }}{% if period == 'custom' %}&period_begin={{ period_begin }}&period_end={{ period_end }}{% endif %}";

    $(function() {
        $('#menu li a').each(function () {
            $(this).attr("href", $(this).attr("href") + sidebarLink);
        });
        $("#periodInterval input").attr(parsley_rules);
    });
</script>

{% block script %}
{% endblock %}

{% endblock %}

measures/templates/measures/create.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <h1>Registrar medida</h1>
        <form action="/measures/create" method="post">{% csrf_token %}
            {{ form.non_filed_errors }}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag}}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <input type="hidden" name="user" value="{{ request.user.id }}">
            <button class="btn btn-success" type="submit">Registrar</button>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $('form').parsley();
</script>
{% endblock %}

measures/templates/measures/edit.html
{% extends "base.html" %}

{% block title %}
Editar | Minhas Medicões
{% endblock %}

{% block main_content %}
<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <form class="content-box" action="{{ request.path }}" method="post">{% csrf_token %}
            <h2 class="content-box-header">Editar Medição</h2>
            <div class="content-box-body">
                <div class="row">
                    <!-- Measure Type -->
                    <div class="form-group col-md-6">
                        <div class="input-group fill-parent">
                            {{ form.measure_type.label_tag }}
                            {{ form.measure_type }}
                        </div>
                        {{ form.measure_type.errors }}
                    </div>
                    <!-- Value -->
                    <div class="form-group col-md-6">
                        <div class="input-group fill-parent">
                            {{ form.value.label_tag }}
                            {{ form.value }}
                        </div>
                        {{ form.value.errors }}
                    </div>
                    <input name="return_path" type="hidden" value="{{ return_path }}">
                </div>
                <!-- Datetime -->
                <div class="form-group">
                    {{ form.datetime.label_tag }}
                    <div id="datetime_picker" class="input-group dp">
                        {{ form.datetime }}
                        <span class="input-group-addon pointer">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    {{ form.datetime.errors }}
                </div>

                <!-- Notes -->
                <div class="form-group">
                    <div class="input-group fill-parent">
                        {{ form.notes.label_tag }}
                        {{ form.notes }}
                    </div>
                    {{ form.notes.errors }}
                </div>
                <!-- User (hidden) -->
                <input type="hidden" name="user" value="{{ request.user.id }}">

            </div>
            <div class="content-box-footer t-right">
                <a href="{{ return_path }}"class="btn btn-default" type="submit">Voltar</a>
                <button class="btn btn-danger" type="submit">Editar</button>
            </div>
        </form>

    </div>
</div>
{% endblock %}

measures/templates/measures/index.html
{% extends "measures/base.html"  %}

{% block head %}
<style media="screen">
    #pie_chart {
        min-width: 310px;
        height: 316.007px;
        max-width: 600px;
        margin: 0 auto;
    }
    #line_chart {
        min-width: 310px;
        height: 380px;
        margin: 0 auto
    }
</style>
{% endblock %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<form class="form-box" action="." method="post">{% csrf_token %}
    <h4 class="form-box-title">Como está o seu nível de glicose no momento?</h4>
    <div class="form-box-content">
        <div class="row">
            <div class="col-xs-7 col-sm-9 col-md-9">
                <div class="form-group">
                    <div class="input-group">
                        {{ form.value }}
                        <span class="input-group-addon">mg/dL</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-5 col-sm-3 col-md-3">
                <div class="form-group">
                    <div class="input-group fill-parent">
                        {{ form.measure_type }}
                    </div>
                </div>
            </div>
        </div>
        <div id="notes" class="form-group" style="display:none">
            {{ form.notes.label_tag }}
            <div class="input-group fill-parent">
                {{ form.notes }}
            </div>
        </div>
        <input type="hidden" name="datetime">
        <input type="hidden" name="user" value="{{ request.user.id }}">
    </div>
    <div class="form-box-actions">
        <a id="notesBtn" onclick="toggleNotesFormGroup()" class="btn btn-default">Adicionar notas</a>
        <button type="submit" class="btn btn-danger">Registrar</button>
    </div>
</form>

{% if queryset %}
<div class="row">
    <!-- Last Measures -->
    <div class="col-md-6">
        <div class="content-box">
            <h4 class="content-box-header">Minhas últimas medições</h4>
            <div class="content-box-body no-padding">
                <div class="list-group">
                    {% for instance in last %}
                    <a href="" class="list-group-item">
                        <h4 class="list-group-item-heading">{{ instance.value }} mg/dL</h4>
                        <div class="list-group-item-text">{{ instance.datetime | timesince }} atrás</div>
                    </a>
                    {% empty %}
                    <div class="list-group-item">
                        Nenhuma medida encontrada.
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="content-box-footer">
                <a type="button" href="/measures/list" class="btn btn-danger fill-parent">Ver todas</a>
            </div>
        </div>
    </div>
    <!-- Pie Chart -->
    <div class="col-md-6">
        <div class="content-box">
            <h4 class="content-box-header"> Distribuição dos registros de glicose no sangue</h4>
            <div class="content-box-body">
                <div id="pie_chart"></div>
            </div>
        </div>
    </div>
</div>
<!-- Area Chart -->
{% if queryset.count > 1 %}
<div class="content-box">
    <div class="content-box-header">
        <h4>Nivel de glicose no sangue durante o período</h4>
    </div>
    <div class="content-box-body">
        <div id="line_chart"></div>
    </div>
</div>
{% endif %}
{% else %}
<div class="content-box">
    <h4 class="content-box-header">Nenhum resultado encontrado</h4>
    <div class="content-box-body">
        <p>Nenhum registro encontrado para o período em questão.</p>
    </div>
</div>
{% endif %}
{% endblock %}

{% block script %}
<script type="text/javascript">
    var overlay = {
        data  : {{ overlay.data   | safe }},
        labels: {{ overlay.labels | safe }},
    }

    var distribution = {
        hypo: {{ distribution.hypo }},
        norm: {{ distribution.norm }},
        pre : {{ distribution.pre  }},
        high: {{ distribution.high }},
    }

    $(document).ready(function () {
        // Append current datetime before form submit
        $("form").submit(function () {
            $("[name='datetime']").val(moment().format("DD/MM/YYYY HH:mm"));
            return true;
        });
        // Render charts
        renderPieChart(distribution);
        renderLineChart(overlay.data, overlay.labels);
    })
</script>
{% endblock %}

measures/templates/measures/list.html
{% extends "measures/base.html" %}
{% load bootstrap_pagination %}

{% block title %}
Minhas Medições
{% endblock %}

{% block content %}

{% include "measures/modal/delete_alert.html" %}
<div class="content-box">
    <div class="content-box-header">
        <div class="row">
            <div class="col-xs-8 col-md-8">
                <h2>Minhas Medições</h2>
            </div>
            {% if queryset %}
            <div class="col-xs-4 col-md-4 t-right">
                <form action="/measures/export_pdf" method="get">
                    {% for key, value in request.GET.items %}
                    <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endfor %}
                    <button type="submit" class="btn btn-danger">Gerar PDF</a>
                </form>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="content-box-body no-padding">
        <div class="list-group">
            {% for instance in queryset %}
            <div class="list-group-item">
                <div class="row">
                    <div class="col-xs-7 col-sm-7 col-md-7">
                        <h4>{{ instance.value }} mg/dL</h4>
                        <div class="list-group-item-text">{{ instance.datetime | date }}</div>
                        <div class="list-group-item-text">{{ instance.datetime | time:"H:i" }}</div>
                        <span class="label label-{{ instance.measure_type | lower }}">{{ instance.get_measure_type_display }}</span>
                    </div>
                    <div class="col-xs-5 col-sm-5 col-md-5">
                        <div class="dropdown f-right">
                            <button class="btn btn-sm btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Ações
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
                                <li><a href="/measures/edit/{{ instance.id }}"><i class="glyphicon glyphicon-pencil" style="margin-right: 10px"></i> EDITAR</a></li>
                                <li><a href="#" onclick="displayDeleteAlert({{ instance.id }})"><i class="glyphicon glyphicon-trash"  style="margin-right: 10px"></i> EXCLUIR</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="list-group-item">
                Nenhum resultado encontrado
            </div>
            {% endfor %}
        </div>
    </div>

    {% if queryset.paginator.num_pages > 1 %}
    <div class="content-box-footer">
        <div class="text-center">
            {% bootstrap_paginate queryset %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

measures/templates/measures/sidebar.html
<form class="form-box" action="{{ request.path }}" method="get">
    <h4 class="form-box-title">Filtros</h4>
    <div class="form-box-content">
        <div class="form-group">
            <div class="input-group input-group-sm fill-parent">
                <select class="form-control" name="period" onchange="displayPeriodInterval()">
                    <option value="today"  {% if period == 'today' %}selected{% endif %}>Hoje</option>
                    <option value="30"     {% if period == '30' %}selected{% endif %}>Último mês</option>
                    <option value="60"     {% if period == '60' %}selected{% endif %}>Últimos 2 meses</option>
                    <option value="all"    {% if period == 'all' %}selected{% endif %}>Desde o começo</option>
                    <option value="custom" {% if period == 'custom' %}selected{% endif %}>Especificar período</option>
                </select>
            </div>
        </div>
        <div id="periodInterval" class="dp-linked row" style="{% if period != 'custom' %} display:none {% endif %}">
            <div class="form-group col-md-12 col-sm-6">
                <div class='input-group input-group-sm fill-parent date dp'>
                    <input type='text' name="period_begin" class="form-control" placeholder="INÍCIO" data-date-format='DD/MM/YYYY' value="{{ period_begin }}"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="form-group col-md-12 col-sm-6">
                <div class='input-group input-group-sm fill-parent date dp'>
                    <input type='text' name="period_end" class="form-control" placeholder="FIM" data-date-format='DD/MM/YYYY' value="{{ period_end }}"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-box-actions t-right">
        <button type="submit" class="btn btn-danger">Filtrar</button>
    </div>
</form>


<div class="sidebar">
    <div>
        <ul id="menu" class="nav nav-sidebar">
            <li id="home" {% if tab == 'home' %}class="active"{% endif %}><a href="/measures/">Principal</a></li>
            <li id="list" {% if tab == 'list' %}class="active"{% endif %}><a href="/measures/list">Minhas medições</a></li>
        </ul>
    </div>
</div>